FROM duckietown/rpi-ros-kinetic-base:master19

RUN [ "cross-build-start" ]

# Argumens for where the different places from which we will get files from are
ARG acquisition_src_dir=ros-cslam/src

# Create a directory to store the Python files and the April tag library
RUN mkdir /acquisition_node

# Install
RUN apt-get update
RUN apt-get install -y --allow-unauthenticated ros-kinetic-rospy
RUN apt-get install -y --allow-unauthenticated python-pip; pip install pathos multiprocessing-logging

# Setup the duckietown_msgs
#RUN mkdir -p /catkin-ws/src
#RUN /bin/bash -c "source /opt/ros/kinetic/setup.bash; cd /catkin-ws/; catkin_make"
#COPY ${acquisition_src_dir}/duckietown_msgs /catkin-ws/src/duckietown_msgs
#RUN /bin/bash -c "source /catkin-ws/devel/setup.bash; cd /catkin-ws/; catkin_make"

# Copy the Python files
COPY ${acquisition_src_dir}/acquisition_node/acquisitionProcessor.py /acquisition_node
COPY ${acquisition_src_dir}/acquisition_node/serverSidePublisher.py /acquisition_node
COPY ${acquisition_src_dir}/acquisition_node/acquire_and_publish.py /acquisition_node
RUN chmod +x /acquisition_node/*.py

ENV ACQ_POSES_UPDATE_RATE 10
ENV ACQ_TOPIC_RAW camera_node/image/compressed
ENV ACQ_DEVICE_MODE live
ENV ACQ_SERVER_MODE live
ENV ACQ_DEVICE_NAME watchtower01
ENV ACQ_ROS_MASTER_URI_DEVICE_IP 192.168.1.30
ENV ACQ_ROS_MASTER_URI_DEVICE_PORT 11311
ENV ACQ_ROS_MASTER_URI_SERVER_IP 192.168.1.70
ENV ACQ_ROS_MASTER_URI_SERVER_PORT 11311

RUN [ "cross-build-end" ]

# Start the processes
CMD /bin/bash -c "cd /acquisition_node; source /opt/ros/kinetic/setup.bash; python acquire_and_publish.py"
